バイナリー存在チェックはスクリプトの最初で行う

diff --git a/bin/phpcs b/bin/phpcs
--- a/bin/phpcs
+++ b/bin/phpcs
@@ -9,6 +9,12 @@ export PHPCS_STANDARD=${PHPCS_STANDARD:-"$DIR/phpcs-standard.xml"}
 # 利用する phpcs バイナリ
 export PHPCS_BIN="${PHPCS_BIN:-$DIR/lib/PHP_CodeSniffer/scripts/phpcs}"
 
+# 見つからないときはエラーで終了
+if ! hash "$PHPCS_BIN" 2>/dev/null; then
+  echo '$PHPCS_BIN must be specified.' "$PHPCS_BIN": not found 1>&2
+  exit 1;
+fi
+
 # 差分情報をスクリプトに渡して phpcs 結果を得る
 bash "$DIR/src/git-diff-staging-files.sh" \
   | perl "$DIR/src/main.pl" --standard="$PHPCS_STANDARD"
